# Generated by Django 4.0.8 on 2024-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_about_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(),
        ),
    ]
