# Generated by Django 4.0.8 on 2024-07-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_seo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'seo', 'verbose_name_plural': 'seo'},
        ),
    ]
